name: Deploy

on:
  push:
    paths:
      - src/**
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1  
      - name: Create .env file
        run: |
          echo "VITE_APP_VERSION=${{ steps.package-version.outputs.current-version }}" > .env
          echo "VITE_BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> .env
      - name: Build
        run: | 
          npm install
          npm run build --production
      - name: Upload via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_LOGIN }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./dist"
          remote_dir: "./"
