name: Deploy

on:
  push:
    paths:
      - src/**
      - public/**
      - index.html
      - package.json
      - .github/workflows/deploy.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1  
      - name: Create .env file
        run: |
          echo "VITE_APP_VERSION=${{ steps.package-version.outputs.current-version }}" > .env
          echo "VITE_BUILD_TIME=$(date +'%Y-%m-%d %H:%M:%S')" >> .env
      - name: Build
        run: | 
          npm install
          npm run build --production
      - name: Upload via FTP
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_LOGIN: ${{ secrets.FTP_LOGIN }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq lftp
          lftp -c "
            set cmd:fail-exit yes;
            set net:max-retries 3;
            set net:timeout 20;
            open -u \"$FTP_LOGIN\",\"$FTP_PASSWORD\" \"$FTP_SERVER\";
            mirror --reverse --verbose ./dist/ ./;
          "
